### ISSUE TITLE
Multiple LDAP servers

### ISSUE THREAD

**Issue by phpfile** [designbyfront/LDAP-Authentication-for-ExpressionEngine#2]
Is there a way we can modify this to work with more then one LDAP server?
I am building an Intranet for our company and we have more then one Active Directory that we want to authenticate with.

**Comment by designbyfront** [comment]
Hi Daniel,

Thanks for the feature request. I've added support for authenticating against multiple LDAP servers - simply add them comma delimited in the 'Server Address' field.

I have assumed that the LDAP servers would all have the same settings (port, search base, search user, etc.). Is this this case, or would each server have its own specific settings?

Regards,
Alistair

**Comment by phpfile** [comment]
Hi Alistair,

Thank you very much for your assistance.
In our case each server has its own specific settings.

Thanks again for your help and hope this isn't very difficult to achieve.

Best regards,
Daniel
