### ISSUE TITLE
Message: Undefined property: EE::$member_model

### ISSUE THREAD

**Issue by osb** [designbyfront/LDAP-Authentication-for-ExpressionEngine#4]
Hi front, 

I'm testing this extension and seem to be running into this error:

A PHP Error was encountered

Severity: Notice
Message: Undefined property: EE::$member_model
Filename: nce_ldap/ext.nce_ldap.php
Line Number: 286

Ever seen this? Everything seems to be validating according to the debug output until after Inserting user with data.

**Comment by swatkins** [comment]
This was my fix:

http://github.com/designbyfront/LDAP-Authentication-for-ExpressionEngine/issues/closed#issue/3

**Comment by osb** [comment]
ah thank you very much my friend. you are awesome. front, please close this. swatkin's fixes worked great.
