### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by jrhoades** [designbyfront/LDAP-Authentication-for-ExpressionEngine#5]
Hi,

in the create_ee_user function around line 294:
    $this->EE->db->query('INSERT INTO exp_member_data... 
 &  
    $this->EE->db->query('INSERT INTO exp_member_homepage...

Both causes unique DB errors as I think the $this->EE->member_model->create_member now creates the DB entries for you.  If I comment them out then new users register fine.

Also in the same function you have hard coded the group_id to be 6, in my particular case the member group_id was 5 - no big deal, but perhaps make it a config option?

Cheers Jon

**Comment by designbyfront** [comment]
Hi Jon,

Thank you for this bug fix!
I've commented out these lines and I've added in member group id as a setting so it can be changed.

Thanks again.
Regards,
Alistair
